name: BloodLink - Desarrollo
values:
  - key: baseUrl
    value: 'http://localhost:3006/api/v1'
    enabled: true
  - key: tokenAdmin
    value: ''
    enabled: true
  - key: refreshTokenAdmin
    value: ''
    enabled: true
  - key: tokenDonor
    value: ''
    enabled: true
  - key: refreshTokenDonor
    value: ''
    enabled: true
  - key: tokenStaff
    value: ''
    enabled: true
  - key: refreshTokenStaff
    value: ''
    enabled: true
  - key: userId
    value: ''
    enabled: true
  - key: targetUserId
    value: ''
    enabled: true
  - key: roleName
    value: STAFF_ROLE
    enabled: true
  - key: testEmail
    value: juan.perez.blood@example.com
    enabled: true
  - key: testUsername
    value: juanblood
    enabled: true
  - key: testPassword
    value: Password123
    enabled: true
  - key: newPassword
    value: NewPassword456
    enabled: true
  - key: testPhone
    value: '12345678'
    enabled: true
  - key: adminEmail
    value: admin@bloodlink.local
    enabled: true
  - key: adminPassword
    value: Admin1234
    enabled: true
  - key: staffEmail
    value: staff@bloodlink.local
    enabled: true
  - key: staffPassword
    value: Staff1234
    enabled: true
  - key: verificationToken
    value: ''
    enabled: true
  - key: activationCode
    value: ''
    enabled: true
  - key: resetToken
    value: ''
    enabled: true
