services:
  postgres:
    image: postgres:16
    container_name: bloodlink-postgres
    restart: always
    environment:
      POSTGRES_DB: bloodlink
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: bloodlink-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data:

